name: dart_mappable_builder
description: Improved json serialization and data classes with full support for generics, inheritance, customization and more.
version: 4.5.0
repository: https://github.com/schultek/dart_mappable
issue_tracker: https://github.com/schultek/dart_mappable/issues
funding:
  - https://github.com/sponsors/schultek

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  analyzer: ^7.0.0
  ansicolor: ^2.0.1
  build: ^2.4.2
  collection: ^1.15.0
  dart_mappable: 
    path: ../dart_mappable
  dart_style: ^3.0.1
  glob: ^2.1.0
  path: ^1.8.0
  pub_semver: ^2.1.5
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  build_test: ^2.2.3
  lints: '>=1.0.0 <6.0.0'
  test: ^1.25.10

